# Análise de Vendas em Python

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dados = {
    'data': ['2024-01-05','2024-01-10','2024-02-03','2024-02-15','2024-03-01'],
    'produto': ['Notebook','Mouse','Notebook','Teclado','Mouse'],
    'quantidade': [2,5,1,3,4],
    'preco': [3500,80,3500,150,80]
}

df = pd.DataFrame(dados)
df

         data   produto  quantidade  preco
0  2024-01-05  Notebook           2   3500
1  2024-01-10     Mouse           5     80
2  2024-02-03  Notebook           1   3500
3  2024-02-15   Teclado           3    150
4  2024-03-01     Mouse           4     80

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   data        5 non-null      object
 1   produto     5 non-null      object
 2   quantidade  5 non-null      int64
 3   preco       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [ ]:
df['faturamento'] = df['quantidade'] * df['preco']
df

         data   produto  quantidade  preco  faturamento
0  2024-01-05  Notebook           2   3500         7000
1  2024-01-10     Mouse           5     80          400
2  2024-02-03  Notebook           1   3500         3500
3  2024-02-15   Teclado           3    150          450
4  2024-03-01     Mouse           4     80          320

In [ ]:
df['faturamento'].sum()

np.int64(11670)

In [ ]:
df.groupby('produto')['quantidade'].sum().sort_values(ascending=False)

produto
Mouse       9
Notebook    3
Teclado     3
Name: quantidade, dtype: int64

In [ ]:
df['data'] = pd.to_datetime(df['data'])

vendas_mes = df.groupby(df['data'].dt.month)['faturamento'].sum()
vendas_mes

data
1    7400
2    3950
3     320
Name: faturamento, dtype: int64

## Conclusão

Este projeto demonstrou:
- Manipulação de dados com pandas
- Criação de métricas de negócio
- Visualização de dados com matplotlib